name: capstone_ui
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  
  flutter_screenutil: ^3.0.1
  flutter_svg: ^1.1.4
  provider: ^6.0.3
  http: ^0.13.0-nullsafety.0
  shared_preferences: ^2.0.15



    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_tts: ^3.5.3
  animated_splash_screen: ^1.3.0
  lottie: ^1.4.1
  page_transition: ^2.0.9
  video_player: ^2.4.6
  permission_handler: ^10.0.0
  speech_to_text: ^5.6.1
  avatar_glow: ^2.0.2
  highlight_text: ^1.4.1
  clipboard: ^0.1.3
  url_launcher: ^6.1.5
    # audioplayers: ^1.0.1
  path_provider: ^2.0.11
  sizer: ^2.0.15
  firebase_auth: ^4.1.1
  firebase_core: ^2.1.1
  pinput: ^2.2.12
  flutterfire_cli: ^0.2.6
  firebase_storage: ^11.0.4
  firebase_messaging: ^14.0.4
  flutter_audio_recorder2: ^0.0.2
  audioplayers: ^0.19.1
  toggle_switch: ^2.0.1
  font_awesome_flutter: ^10.2.1
  getwidget: ^3.0.1
  flutter_bloc: ^8.1.1
  freezed: ^2.1.1
  build_runner: ^2.3.0
  freezed_annotation: ^2.1.0
  confirm_dialog: ^1.0.1
  cached_network_image: ^3.2.2
  file_picker: ^5.0.0
  image_picker: ^0.8.1+3 
  timeago: ^3.3.0
  youtube_player_flutter: ^8.1.1
  flutter_inappwebview: ^5.5.0+4
  like_button: ^2.0.5
  cloud_firestore: ^4.0.5
  fluttertoast: ^8.1.1
  photo_view: ^0.14.0
  flutter_datetime_picker: ^1.5.1
  intl: ^0.17.0
  get: ^4.6.5
  flutter_local_notifications: ^12.0.3
  search_helper: ^0.0.7
  readmore: ^2.2.0
  form_field_validator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Gotham
      fonts:
        - asset: assets/fonts/Gotham-XLight.otf
    - family: GothamB
      fonts:
        - asset: assets/fonts/GothamMedium.ttf
    - family: San
      fonts:
        - asset: assets/fonts/SourceSansPro-Light.ttf

  assets:
  - assets/images/
  - assets/icons/
  - assets/fonts/
  - assets/lottie/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
